### ISSUE TITLE
Integrate functional tests

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/gradle-aem-multi#32]
configure https://github.com/smooth-code/jest-puppeteer in https://github.com/Cognifide/gradle-aem-multi/tree/flat-structure/test.functional/  build.gradle.kts

**Comment by pun-ky** [comment]
use instead https://www.cypress.io/

**Comment by mealtdown** [comment]
Ok I'd like to own the ticket.

**Comment by pun-ky** [comment]
Done
