### ISSUE TITLE
Introduce sample servlet using Sling Servlet Annotations 

### ISSUE THREAD

**Issue by tenzo** [Cognifide/gradle-aem-multi#40]
I tried to add dependencies to gradle project for new Servlet Annotations (described here:
https://sling.apache.org/documentation/the-sling-engine/servlets.html#registering-a-servlet-using-java-annotations),
but with no success. I think I miss proper plugin. How to do this the right way?

**Comment by pun-ky** [comment]
Thanks for reporting this. When I find some time (within next month) I will include appropriate servlet example in this project.

**Comment by pun-ky** [comment]
done, code copied from archetype already have it
