### ISSUE TITLE
Extract dispatcher configuration to project archetypes

### ISSUE THREAD

**Issue by mierzwid** [Cognifide/gradle-aem-multi#53]
Allow users of project archetypes to also fork dispatchers configuration and provide its details specific for the project.

# AC
* when forking gradle-aem-multi
    * dev is asked to provide names for demo and live local domains
    * aemEnvHosts task is configured accordingly
    * reverse mappings are generated
    * invalidation handler is configured
    * whole httpd and dispatchers configuration files are generated
    * basic health checks are generated
    * user can start dispatchers development out of the box

Related #78, #355.

**Comment by pun-ky** [comment]
outdated
