### ISSUE TITLE
Replication issues

### ISSUE THREAD

**Issue by wow64ext** [Cognifide/gradle-aem-multi#83]
The replication agent on publish in disabled by default which is causing some trouble while working with the instances.

**Comment by pun-ky** [comment]
@mierzwid has been confiiguring this and checking. Are you sure? When impl provisioning then multi on branch could have broken that agents accidentally by provisioning but on master it remained as @mierzwid leaved. If you are sure please fix it / create PR

**Comment by pun-ky** [comment]
probably password is encrypted and salt used in encryption is generated every AEM instances are created. to be confirmed

**Comment by pun-ky** [comment]
probably fixed in https://github.com/Cognifide/gradle-aem-multi/pull/85/commits/fed5e7d2d9f5a787ac657aab3bbf186f18b3f222

**Comment by pun-ky** [comment]
Done
